youtube_channel_ids:
  - UC8wZnXYK_CGKlBcZp-GxYPA
  - UCDq7SjbgRKty5TgGafW8Clg
  - UC-zVytOQB62OwMhKRi0TDvg
  - UCadVGkh-CrparnJIgmv5Iuw
  - UCgBncpylJ1kiVaPyP-PZauQ
  - UCgLxmJ8xER7Y7sywMN5SfWg
  - UCZovC61jTNT1aQ_JDFoeZwQ
  - UCoW_WzQNJVAjxo4osNAxd_g
  - UCAEOtPgh29aXEt31O17Wfjg
  - UCtAcpQcYerN8xxZJYTfWBMw
  - UC_CzsS7UTjcxJ-xXp1ftxtA
  - UCn8ujwUInbJkBhffxqAPBVQ
max_results: 50
chunk_size: 512
embedding_model: nomic-ai/modernbert-embed-base
reranker_model: cross-encoder/ms-marco-MiniLM-L-12-v2
llm:
  contextual_chunking: llama-3.1-8b-instant
  rag: llama-3.3-70b-versatile
temperature:
  contextual_chunking: 0.0
  rag: 1.0
max_output_tokens:
  contextual_chunking: 1024
  rag: 4096
k: 3
threshold: 0.9
youtube_search_url: https://www.youtube.com/results?search_query
